FROM alpine:3.11

RUN apk add ca-certificates tzdata
WORKDIR /app

COPY zoneinfo.zip /app/zoneinfo.zip
ENV ZONEINFO /app/zoneinfo.zip

COPY ./build/service_settings /app/service_settings

ENTRYPOINT ["/app/service_settings"]