// Code generated by mockery v2.2.1. DO NOT EDIT.

package validators

import (
	models "github.com/Confialink/wallet-settings/internal/db/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSettingValidator is an autogenerated mock type for the SettingValidator type
type MockSettingValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: data
func (_m *MockSettingValidator) Validate(data []*models.Config) *ValidationError {
	ret := _m.Called(data)

	var r0 *ValidationError
	if rf, ok := ret.Get(0).(func([]*models.Config) *ValidationError); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ValidationError)
		}
	}

	return r0
}
