// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/proto/settings/settings.proto

package settings

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Setting struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc9b4a3f94e52e5, []int{0}
}

func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (m *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(m, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Setting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Request struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc9b4a3f94e52e5, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Response struct {
	Setting              *Setting   `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	Settings             []*Setting `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty"`
	Error                *Error     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc9b4a3f94e52e5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSetting() *Setting {
	if m != nil {
		return m.Setting
	}
	return nil
}

func (m *Response) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Details              string   `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc9b4a3f94e52e5, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Error) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*Setting)(nil), "velmie.wallet.settings.Setting")
	proto.RegisterType((*Request)(nil), "velmie.wallet.settings.Request")
	proto.RegisterType((*Response)(nil), "velmie.wallet.settings.Response")
	proto.RegisterType((*Error)(nil), "velmie.wallet.settings.Error")
}

func init() {
	proto.RegisterFile("rpc/proto/settings/settings.proto", fileDescriptor_7dc9b4a3f94e52e5)
}

var fileDescriptor_7dc9b4a3f94e52e5 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xa5, 0x76, 0x6b, 0xd7, 0xf1, 0x20, 0x0c, 0x22, 0x45, 0x58, 0x5c, 0x7b, 0xf2, 0x94, 0x85,
	0xed, 0x41, 0xc4, 0x9b, 0x20, 0xae, 0xe0, 0x29, 0xde, 0xbc, 0x45, 0x77, 0xd0, 0x40, 0x6c, 0x6b,
	0x32, 0xbb, 0xfe, 0x91, 0xbf, 0xe0, 0xef, 0xe9, 0xa6, 0x49, 0x4f, 0x2d, 0x78, 0xf0, 0x36, 0x6f,
	0xe6, 0xbd, 0xcc, 0x9b, 0x47, 0xe0, 0xdc, 0xb6, 0x2f, 0x8b, 0xd6, 0x36, 0xdc, 0x2c, 0x1c, 0x31,
	0xeb, 0xfa, 0xd5, 0xf5, 0x85, 0xf0, 0x7d, 0x3c, 0xd9, 0x92, 0x79, 0xd7, 0x24, 0x3e, 0x95, 0x31,
	0xc4, 0x22, 0x4e, 0xcb, 0x0a, 0xf2, 0xc7, 0xae, 0x46, 0x84, 0x49, 0xab, 0xf8, 0xad, 0x48, 0xe6,
	0xc9, 0xc5, 0x81, 0xf4, 0x35, 0x1e, 0x43, 0xb6, 0x55, 0x66, 0x43, 0xc5, 0x9e, 0x6f, 0x76, 0xa0,
	0x9c, 0x41, 0x2e, 0xe9, 0x63, 0x43, 0x8e, 0x87, 0x44, 0xe5, 0x77, 0x02, 0x53, 0x49, 0xae, 0x6d,
	0x6a, 0x47, 0x78, 0x05, 0x79, 0x58, 0xe6, 0x39, 0x87, 0xcb, 0x33, 0x31, 0x6c, 0x45, 0x04, 0x1f,
	0x32, 0xf2, 0xf1, 0x1a, 0xa6, 0x71, 0xf8, 0xbb, 0x3f, 0xfd, 0x8b, 0xb6, 0x17, 0x60, 0x05, 0x19,
	0x59, 0xdb, 0xd8, 0x22, 0xf5, 0x5b, 0x67, 0x63, 0xca, 0xdb, 0x1d, 0x49, 0x76, 0xdc, 0xf2, 0x12,
	0x32, 0x8f, 0x77, 0x77, 0xb3, 0x66, 0x43, 0xe1, 0xae, 0x0e, 0x60, 0x01, 0xf9, 0x9a, 0x58, 0x69,
	0xe3, 0x42, 0x1e, 0x11, 0x2e, 0xbf, 0x12, 0x38, 0x0a, 0x1e, 0xdc, 0x4a, 0xd5, 0x6b, 0x43, 0x16,
	0x57, 0x90, 0xde, 0x11, 0xe3, 0xa8, 0xe7, 0x10, 0xe1, 0xe9, 0x7c, 0x9c, 0x10, 0x32, 0xbc, 0x87,
	0xc9, 0x83, 0x76, 0xff, 0xf1, 0xd4, 0x0d, 0x3c, 0xf5, 0x11, 0x3d, 0xef, 0xfb, 0xaf, 0x51, 0xfd,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x97, 0x1b, 0x6a, 0x3f, 0x02, 0x00, 0x00,
}
